/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jedis;

import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.Protocol.Command;
import redis.clients.jedis.util.SafeEncoder;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try (JedisPool pool = new JedisPool("localhost", 6379)) {
            try (Jedis jedis = pool.getResource()) {
                String key = "titi";
                jedis.set(key, "toto");
                String str = jedis.get(key);
                System.out.println("str: " + str);

                String command = "SET";

                jedis.sendCommand(Command.valueOf(command.trim().toUpperCase()), key, "tutu");

                Object response = jedis.sendCommand(Command.valueOf("GET"), key);
                System.out.println("str2: " + SafeEncoder.encode((byte[]) response));
            }
        }
    }
}
